### ISSUE TITLE
Why Use Camera Distance as a Dividing Form?

### ISSUE THREAD

**Issue by jk4011** [kxhit/EscherNet#10]
First of all, I want to express my gratitude for your outstanding research. I thoroughly enjoyed reading your paper.

However, I have a question regarding the encoding used in your work. I noticed that the encoding equation for [`azimuth`, `elevation`, `orientation`] differs from that of [`camera distance`]. Specifically, I am unsure why the camera distance requires a dividing form. Could you help me understand the reasoning behind this choice? I feel like I might be missing an important detail.

Thank you very much for your assistance.

<img width="620" alt="image" src="https://github.com/kxhit/EscherNet/assets/60100980/65ef85f7-b1ad-47cc-97da-8fb36c61ccf1">

**Comment by lorenmt** [comment]
Hi @jk4011, please consider the design of CaPE in the sense of equivalence -- we want to design CaPE in a way such that changing camera coordinates would lead to the identical features / attention maps.

In terms of camera angle -- the equivalence is relative difference -- e.g. 20 to 40 degree difference is the same as 40 to 60.
In terms of distance however -- the equivalent is relative division -- e.g. 2 to 4 meter difference is the same as 4 to 8 meter difference (you move the camera twice further -- objects are two times smaller).

Another way to understand is try to imagine we are rotating the 2D coordinates: in angel difference -- we are rotating the coordinate system; in distance difference -- we are squeezing / expanding the coordinate system.
