### ISSUE TITLE
Novel view synthesis from a single image

### ISSUE THREAD

**Issue by dhsoon02** [kxhit/EscherNet#11]
Dear Authors
First, thank you for your interesting and amazing work.

I would like to do the Novel view synthesis task using my own single rgba image, in this case, should the data_type be Text2Img?
If I put only one image as input, I wonder if it will work with other data_type as well. 

Thanks for the great work!!!

**Comment by kxhit** [comment]
Single image should work. I think you can use data_type "Text2Img" and make sure this [line](https://github.com/kxhit/EscherNet/blob/569240f81d729aae413167a898c2af21dc969dd2/eval_eschernet.py#L407C25-L407C33) loads your image correctly.

**Comment by dhsoon02** [comment]
Thank you for your kind response.

I have one thing I would like to confirm.

When I used "Text2Img" as the data_type, it worked fine.
Do you think that changing the data_type to another option (e.g. GSO, RTMV, Franka, etc.) will still work with just a single RGBA image?

If it works with other data_types, will we need any additional data besides the RGBA image?

**Comment by kxhit** [comment]
@dhsoon02 Hi, the different data_types are just for supporting different camera coordinates and number of images. Basically, you could modify according to your camera setting, as long as your input to EscherNet contains input images (T_in >= 1) and their poses and the queried output poses (T_out >= 1), in OpenGL object coordinates.
