### ISSUE TITLE
Question about process of predicted image

### ISSUE THREAD

**Issue by wangyuyy** [kxhit/EscherNet#19]
Hi, thanks for your excellent work!
I noticed that in [pipeline.decode_latents](https://github.com/kxhit/EscherNet/blob/main/6DoF/pipeline_zero1to3.py#L607), the output image of vae.decode is scaled by `(image / 2) + 0.5`. 
And in [train.py log_validation](https://github.com/kxhit/EscherNet/blob/main/6DoF/train_eschernet.py#L138), the pred_image is scaled back by `image * 2 - 1`.
However, in [eval_eschernet.py](https://github.com/kxhit/EscherNet/blob/main/eval_eschernet.py#L537), the pred_image is directly converted to numpy and saved without scaling backward.
I wonder which scale of the predicted image is expected?

**Comment by kxhit** [comment]
Hi,
the output of vae.decode is [-1,1], thus scaled to [0, 1] by `(image / 2) + 0.5`
the pipeline output in log_validation is [0, 1], so it is scaled back to [-1,1] by `image * 2 - 1` to calculate with gt_image to get metrics
pred_image in eval_eschernet is [0, 1], so it is converted and saved by `Image.fromarray((image[i] * 255).astype(np.uint8)`

the images are usually [-1,1] when it is in the diffusion process, it will be scaled by following the purposes you want.

**Comment by wangyuyy** [comment]
Many thanks for your rapid response !
I have figured out the scale of images in vae and diffusion.
However, I'm still confused of the image scale in `log_validation`. The output of the pipeline `image=pipeline(...)` is [0,1], while the input of wandb.Image, pred_image, is converted into [-1, 1] from `image` by `pred_image = torch.from_numpy(image * 2. - 1.).permute(0, 3, 1, 2)`. Is it feasible to input image with range [-1,1] into wandb.Image?
Moreover, I wonder whether the purpose of [for _ in range(args.num_validation_images):](https://github.com/kxhit/EscherNet/blob/main/6DoF/train_eschernet.py#L133) is to validate with different random number?
Thanks again for your help.

**Comment by kxhit** [comment]
You can double-check wandb.Image function, I think they handle many formats.

Yes, we visualize generation results under the same conditions but with different initial random noise.

**Comment by wangyuyy** [comment]
I got it! many thanks again!
