### ISSUE TITLE
The 3d reconstruction file is missing 

### ISSUE THREAD

**Issue by qianfan01** [kxhit/EscherNet#20]
First of all, thank you very much for your wonderful work, which has given me inspiration in other aspects of my 3D reconstruction. Therefore, I have reproduced your work 
When performing 3d reconstruction, follow the steps in the readme to generate 36 new views with data_type=GSO3D. Run the command bash ./ The directory output by eval_eschernet.sh is as follows: 
 
![图片1](https://github.com/user-attachments/assets/cb695232-3ed0-48ba-84eb-a5d619ea3fb5)

At this point, continue to run the subsequent steps of Neus for 3D reconstruction: python run_NeuS.py 
The following error message appears: FileNotFoundError: No such file: '/home/ChenShi/code/EscherNet/logs_6DoF/GSO3D/logs_GSO_T1M36_99k/mario/0.png' 
This error is caused by my wrong step in running bash ./ Is the output file of eval_eschernet.sh missing

**Comment by kxhit** [comment]
Hi @qianfan01 thanks for your interest in our work!

Could you try to modify this [line](https://github.com/kxhit/EscherNet/blob/10b650492ba97b5104a3136de07d1a67f4ada458/3drecon/run_NeuS.py#L14) to your folder name accordingly.

**Comment by qianfan01** [comment]
收到邮件，空闲时尽快回复您

**Comment by qianfan01** [comment]
Now it can run. Thank you for your help. I wish you smooth research and a pleasant life.
