### ISSUE TITLE
Gradio Demo

### ISSUE THREAD

**Issue by SSamDav** [kxhit/EscherNet#3]
Hi, great work!

Do you plan to release the code to do inference on real word objects?

**Comment by kxhit** [comment]
Hi @SSamDav Thanks for your interest!
We already released the code. Just download the dataset [Franka16](https://github.com/kxhit/EscherNet?tab=readme-ov-file#franka16) and modify the [shell script](https://github.com/kxhit/EscherNet/blob/cf6b220e5085acfad1d20d68afde3e101e2af1e2/eval_eschernet.sh#L38). For your own data, you can just follow the data format and get the image pose with masked images.

**Comment by kxhit** [comment]
@SSamDav 
Hi, we have a public gradio demo hosted on HuggingFace now https://huggingface.co/spaces/kxic/EscherNet
