### ISSUE TITLE
Dust3r pose processing 

### ISSUE THREAD

**Issue by fradif96** [kxhit/EscherNet#7]
Dear authors,
Thank you for the great work! I just checked the online demo that you released few days ago. I have some questions regarding the use of Dust3r to compute initial input poses for EscherNet:

1) Do you apply some modifications to computed output from Dust3r to obtain orthogonal canonical frame ? If yes could you provide more details about them? 

2) For reproducibility could you provide the Dust3r’s code line from which you take and save the computed poses to assign to each input image for EscherNet?

Thanks in advance

**Comment by kxhit** [comment]
Thanks for your interests.
1.Yes, we modified Dust3r. We want to set our novel view poses starting from the top-down view of the object, and we estimated the plane by open3d plane fitting and estimated the normal direction of this plan as the z-up direction. The orthogonal canonical coordinate is not necessary for our EscherNet model, it is only used for better visualisation.
2.THe gradio demo code is here on the [huggingface space](https://huggingface.co/spaces/kxic/EscherNet/tree/main). The estimated poses are assigned to EscherNet [here](https://huggingface.co/spaces/kxic/EscherNet/blob/main/app.py#L487).

Cheers.
