### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by yejr0229** [kxhit/EscherNet#9]
Hi, I'd like to know how much memory is required for EscherNet? An A100 or just RTX3090 with 24GB will be enough?

**Comment by jk4011** [comment]
I'm wondering memory requirement for training, too.

**Comment by kxhit** [comment]
Hi, the training details are in the paper, which requires 6 A100 80GB GPUs to train. But for inference, it takes less than 10GB GPU memory, which can run on a commercial GPU easily.
